# Created with WinGet Releaser using komac v2.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: KRTirtho.Spotube
PackageVersion: 4.0.2
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: inno
Scope: machine
ProductCode: 80B901C8-D6FE-494E-8AF7-A2BD440E8644_is1
ReleaseDate: 2025-03-16
AppsAndFeaturesEntries:
- DisplayVersion: 4.0.2+41
  ProductCode: 80B901C8-D6FE-494E-8AF7-A2BD440E8644_is1
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Spotube'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/KRTirtho/spotube/releases/download/v4.0.2/Spotube-windows-x86_64-setup.exe
  InstallerSha256: D0E1A282D89B59D99C518A8D8DE14CB3CFD1BA02F8AC2AD2CFE06F38004618E7
  InstallerSwitches:
    Custom: /ALLUSERS
- Architecture: x64
  InstallerUrl: https://github.com/KRTirtho/spotube/releases/download/v4.0.2/Spotube-windows-x86_64-setup.exe
  InstallerSha256: D0E1A282D89B59D99C518A8D8DE14CB3CFD1BA02F8AC2AD2CFE06F38004618E7
  InstallerSwitches:
    Custom: /CURRENTUSER
ManifestType: installer
ManifestVersion: 1.9.0

