# Created with WinGet Releaser using komac v2.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: KRTirtho.Spotube
PackageVersion: 4.0.2
PackageLocale: en-US
Publisher: KRTirtho, OSS
PublisherUrl: https://github.com/KRTirtho/spotube
PublisherSupportUrl: https://github.com/KRTirtho/spotube/issues
PrivacyUrl: https://github.com/KRTirtho/spotube/blob/master/PRIVACY_POLICY.md
Author: KRTirtho, OSS
PackageName: Spotube
PackageUrl: https://github.com/KRTirtho/spotube
License: BSD-4-Clause License
LicenseUrl: https://github.com/KRTirtho/spotube/blob/HEAD/LICENSE
Copyright: Copyright (c) 2022 Kingkor Roy Tirtho. All rights reserved.
CopyrightUrl: https://github.com/KRTirtho/spotube/blob/master/LICENSE
ShortDescription: Spotube is a Flutter based lightweight spotify client. It utilizes the power of Spotify & Youtube's public API & creates a hazardless, performant & resource friendly User Experience
Tags:
- audio
- audio-player
- flutter
- music
- music-player
- spotify
- youtube
ReleaseNotes: |-
  Highlights
  - Fixes the empty home screen and "Something went wrong" bug
  Bug Fixes
  - invalid access token exception #2525
  Full Changelog: v4.0.1...v4.0.2
ReleaseNotesUrl: https://github.com/KRTirtho/spotube/releases/tag/v4.0.2
ManifestType: defaultLocale
ManifestVersion: 1.9.0

